  [submodule "codo5"]
    
    url = "https://github.com/yves-haswany/codo5"
[dev]
  command = "npm run dev"
  port = 8888
  publish = ".next"

[build]
publish = ".next"
command = "npm run build"

  [build.environment]
  NODE_VERSION = "20.18.1"
  CONTENTFUL_SPACE_ID = "${CONTENTFUL_SPACE_ID}"
  CONTENTFUL_ENVIRONMENT = "${CONTENTFUL_ENVIRONMENT}"
  CONTENTFUL_PREVIEW_TOKEN = "${CONTENTFUL_PREVIEW_TOKEN}"
  CONTENTFUL_MANAGEMENT_TOKEN = "${CONTENTFUL_MANAGEMENT_TOKEN}"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]
  [context.branch-deploy]
  [context.preview]

